name: Android CI

on:
  push:
    branches: [ master ]
    workflow_dispatch: true
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: show_output
      run: |
        cd app
        ls
        tree
    - name: pack_debug_apk
      uses: actions/upload-artifact@v2
      with: 
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk